"""DB modifica

Revision ID: 0f43091d048e
Revises: 3f1e4a593633
Create Date: 2024-06-06 09:28:35.096161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f43091d048e'
down_revision = '3f1e4a593633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'utenza', ['user_id'], ['id'])

    with op.batch_alter_table('trattamenti', schema=None) as batch_op:
        batch_op.drop_constraint('trattamenti_ibfk_2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trattamenti', schema=None) as batch_op:
        batch_op.create_foreign_key('trattamenti_ibfk_2', 'utenza', ['user_id'], ['id'])

    with op.batch_alter_table('piante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
