"""DB aggiunta piantagione

Revision ID: 4f95b5efbe15
Revises: 0f43091d048e
Create Date: 2024-06-06 10:32:35.505989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f95b5efbe15'
down_revision = '0f43091d048e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piantagione',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=False),
    sa.Column('data_inizio', sa.Date(), nullable=False),
    sa.Column('data_fine', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pianta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pianta_id'], ['piante.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['utenza.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('piante', schema=None) as batch_op:
        batch_op.drop_constraint('piante_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('piante_ibfk_1', 'utenza', ['user_id'], ['id'])

    op.drop_table('piantagione')
    # ### end Alembic commands ###
