"""Add user_id to Trattamenti

Revision ID: 9627283c7ca1
Revises: 
Create Date: 2024-06-02 18:07:31.086174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9627283c7ca1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piante',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('specie', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utenza',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('trattamenti',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pianta_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=False),
    sa.Column('data_inizio', sa.Date(), nullable=False),
    sa.Column('data_fine', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['pianta_id'], ['piante.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['utenza.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Trattamenti')
    op.drop_table('Piante')
    with op.batch_alter_table('Utenza', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('Utenza')
    with op.batch_alter_table('user_plant_treatment', schema=None) as batch_op:
        batch_op.drop_constraint('user_plant_treatment_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('user_plant_treatment_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('user_plant_treatment_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'utenza', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'piante', ['plant_id'], ['id'])
        batch_op.create_foreign_key(None, 'trattamenti', ['treatment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_plant_treatment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_plant_treatment_ibfk_2', 'Piante', ['plant_id'], ['id'])
        batch_op.create_foreign_key('user_plant_treatment_ibfk_3', 'Trattamenti', ['treatment_id'], ['id'])
        batch_op.create_foreign_key('user_plant_treatment_ibfk_1', 'Utenza', ['user_id'], ['id'])

    op.create_table('Utenza',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('cognome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Utenza', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('Piante',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('specie', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Trattamenti',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pianta_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descrizione', mysql.TEXT(), nullable=False),
    sa.Column('data_inizio', sa.DATE(), nullable=True),
    sa.Column('data_fine', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['pianta_id'], ['Piante.id'], name='trattamenti_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('trattamenti')
    op.drop_table('utenza')
    op.drop_table('piante')
    # ### end Alembic commands ###
